###
GET http://localhost:3500/api/racas

###
GET http://localhost:3500/api/racas/1

###
POST http://localhost:3500/api/racas
Content-Type: application/json

{
    "raca" : "Rato"
}

###
PUT http://localhost:3500/api/racas/6
Content-Type: application/json

{
    "raca" : "Pato"
}
###
DELETE http://localhost:3500/api/racas/8
Content-Type: application/json

